apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: florage
  labels:
    app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: ghcr.io/pasinduprabhashitha/florage-authentication-service:master
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: db-connection-secret
                  key: mongo-connection-url
      imagePullSecrets:
        - name: github-cr-access-token-dockerconfigjson

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: florage
spec:
  selector:
    app: authentication-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 80
